# Generated by Django 5.2.6 on 2025-10-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('tea', 'Tea')], max_length=250)),
                ('nutrients', models.CharField(blank=True, max_length=250)),
                ('ingredients', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('available', models.BooleanField(default=True)),
                ('spice_level', models.CharField(choices=[('spicy', 'Spicy'), ('normal', 'Normal'), ('not', 'Not Spicy')], default='normal', max_length=10)),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert')], default='lunch', max_length=20)),
                ('food_type', models.CharField(choices=[('liquid', 'Liquid'), ('light', 'Light'), ('heavy', 'Heavy'), ('solid', 'Solid')], default='heavy', max_length=10)),
                ('nutrient_function', models.CharField(choices=[('fruits', 'Fruits & Vegetables'), ('starchy', 'Starchy Carbohydrates'), ('protein', 'Protein Foods'), ('dairy', 'Dairy & Alternatives'), ('fats', 'Fats & Oils')], default='starchy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avg_prize_for_two', models.PositiveIntegerField(default=200)),
                ('isverified', models.BooleanField(default=False)),
                ('isluxury', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/foodapp/image/restaurants/')),
                ('description', models.TextField(blank=True)),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('subject', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='foodapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('state', models.CharField(default='Maharashtra', max_length=160)),
                ('pincode', models.CharField(default=True, max_length=10)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], max_length=200)),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='foodapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.PositiveIntegerField(default=0)),
                ('offer_valid_until', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='foodapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('pending', 'Pending'), ('on_the_way', 'On the way'), ('delivery', 'Delivery'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, default=True, max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodapp.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodapp.menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodapp.restaurant'),
        ),
    ]
